/* Generated by scripts/generate-catalog.mjs — do not edit by hand */
export type NavItem = { label: string; href: string; source: string; module: string };
export type NavGroup = { label: string; items: NavItem[] };
export const NAV: NavGroup[] = [
  {
    "label": "Admission",
    "items": [
      {
        "label": "Dashboard",
        "href": "/staff/admission/dashboard",
        "source": "/admin/admission/admission_dashboard",
        "module": "admission"
      },
      {
        "label": "Cutoff Setup",
        "href": "/staff/admission/cutofflist",
        "source": "/admin/admission/cutofflist",
        "module": "admission"
      },
      {
        "label": "Import Applicants",
        "href": "/staff/admission/importapplication",
        "source": "/admin/admission/importapplication",
        "module": "admission"
      },
      {
        "label": "Generate Merit List",
        "href": "/staff/admission/generatemeritlist",
        "source": "/admin/admission/generatemeritlist",
        "module": "admission"
      },
      {
        "label": "Manage Admission",
        "href": "/staff/admission/manageadmission",
        "source": "/admin/admission/manageadmission",
        "module": "admission"
      },
      {
        "label": "Selection Status Report",
        "href": "/staff/admission/selection-status-report",
        "source": "/admin/admission/selection_status_report",
        "module": "admission"
      },
      {
        "label": "Summarized Report",
        "href": "/staff/admission/summary-report",
        "source": "/admin/admission/summary_report",
        "module": "admission"
      },
      {
        "label": "Admission Report",
        "href": "/staff/admission/report",
        "source": "/admin/admission/report",
        "module": "admission"
      }
    ]
  },
  {
    "label": "Student Information",
    "items": [
      {
        "label": "Student Details",
        "href": "/staff/student/search",
        "source": "/student/search",
        "module": "students"
      },
      {
        "label": "Student Dashboard",
        "href": "/staff/student/dashboard",
        "source": "/student/student_dashboard",
        "module": "students"
      },
      {
        "label": "Student Admission",
        "href": "/staff/student/create",
        "source": "/student/create",
        "module": "students"
      },
      {
        "label": "Railway Concession",
        "href": "/staff/railway-concession",
        "source": "/railway_concession/index",
        "module": "students"
      },
      {
        "label": "Bulk Update",
        "href": "/staff/student/bulkupdate",
        "source": "/student/bulkupdate",
        "module": "students"
      },
      {
        "label": "Other Course Form",
        "href": "/staff/liberal-art/liberal-art-student",
        "source": "/admin/liberal_art/liberal_art_student",
        "module": "academics"
      },
      {
        "label": "Disabled Students",
        "href": "/staff/student/disablestudentslist",
        "source": "/student/disablestudentslist",
        "module": "students"
      },
      {
        "label": "Bulk Delete",
        "href": "/staff/student/bulkdelete",
        "source": "/student/bulkdelete",
        "module": "students"
      },
      {
        "label": "Student Categories",
        "href": "/staff/category",
        "source": "/category",
        "module": "system"
      },
      {
        "label": "Online Application",
        "href": "/staff/onlinestudent",
        "source": "/admin/onlinestudent",
        "module": "admission"
      },
      {
        "label": "Disable Reason",
        "href": "/staff/disable-reason",
        "source": "/admin/disable_reason",
        "module": "hr"
      },
      {
        "label": "Assign Optional Subject",
        "href": "/staff/student/assign-optional-course",
        "source": "/student/assign_optional_course",
        "module": "students"
      },
      {
        "label": "Semester Allocation",
        "href": "/staff/student/semester-allocation",
        "source": "/student/semester_allocation",
        "module": "students"
      },
      {
        "label": "Student Bulk Upload",
        "href": "/staff/student/student-bulk-upload",
        "source": "/student/student_bulk_upload",
        "module": "students"
      },
      {
        "label": "Generate Roll Number",
        "href": "/staff/student/generaterollnumber",
        "source": "/student/generaterollnumber",
        "module": "students"
      },
      {
        "label": "Approve Optional Subject",
        "href": "/staff/student/approve-optional-course",
        "source": "/student/approve_optional_course",
        "module": "students"
      },
      {
        "label": "Upload Student Documents",
        "href": "/staff/student/upload-student-documents",
        "source": "/student/upload_student_documents",
        "module": "students"
      },
      {
        "label": "Upload Student Photo",
        "href": "/staff/student/upload-student-photo",
        "source": "/student/upload_student_photo",
        "module": "students"
      }
    ]
  },
  {
    "label": "Dashboard",
    "items": [
      {
        "label": "Dashboard",
        "href": "/staff/dashboard",
        "source": "/admin/dashboard",
        "module": "dashboard"
      }
    ]
  },
  {
    "label": "Fees Collection",
    "items": [
      {
        "label": "Collect Fees",
        "href": "/staff/studentfee",
        "source": "/studentfee",
        "module": "fees"
      },
      {
        "label": "Fees Fine Rules",
        "href": "/staff/fine-rules",
        "source": "/admin/fine_rules",
        "module": "fees"
      },
      {
        "label": "Fee Receipt Import",
        "href": "/staff/fee-receipt-import",
        "source": "/admin/fee_receipt_import",
        "module": "fees"
      },
      {
        "label": "Fee Receipt List",
        "href": "/staff/studentfee/feereceipt",
        "source": "/studentfee/feereceipt",
        "module": "fees"
      },
      {
        "label": "Fee Summary Dashboard",
        "href": "/staff/studentfee/fee-summary-dashboard",
        "source": "/studentfee/fee_summary_dashboard",
        "module": "fees"
      },
      {
        "label": "Offline Bank Payments",
        "href": "/staff/offlinepayment",
        "source": "/admin/offlinepayment",
        "module": "fees"
      },
      {
        "label": "Search Fees Payment",
        "href": "/staff/studentfee/searchpayment",
        "source": "/studentfee/searchpayment",
        "module": "fees"
      },
      {
        "label": "Search Due Fees",
        "href": "/staff/studentfee/feesearch",
        "source": "/studentfee/feesearch",
        "module": "fees"
      },
      {
        "label": "Assign Variable Fees",
        "href": "/staff/assign-variable-fees",
        "source": "/admin/assign_variable_fees",
        "module": "fees"
      },
      {
        "label": "Fees Master",
        "href": "/staff/feemaster",
        "source": "/admin/feemaster",
        "module": "fees"
      },
      {
        "label": "Fees Group",
        "href": "/staff/feegroup",
        "source": "/admin/feegroup",
        "module": "fees"
      },
      {
        "label": "Fees Type Group",
        "href": "/staff/fees-type-group",
        "source": "/admin/fees_type_group",
        "module": "fees"
      },
      {
        "label": "Fees Type",
        "href": "/staff/feetype",
        "source": "/admin/feetype",
        "module": "fees"
      },
      {
        "label": "Assign Fee Master",
        "href": "/staff/feemastercoursewise",
        "source": "/admin/feemastercoursewise",
        "module": "fees"
      },
      {
        "label": "Fees Discount",
        "href": "/staff/feediscount",
        "source": "/admin/feediscount",
        "module": "fees"
      },
      {
        "label": "Fees Carry Forward",
        "href": "/staff/feesforward",
        "source": "/admin/feesforward",
        "module": "fees"
      },
      {
        "label": "College Other Fees",
        "href": "/staff/paymentcategory/collegeotherfees",
        "source": "/admin/paymentcategory/collegeotherfees",
        "module": "fees"
      },
      {
        "label": "Fees Reminder",
        "href": "/staff/feereminder/setting",
        "source": "/admin/feereminder/setting",
        "module": "fees"
      },
      {
        "label": "Scholarship",
        "href": "/staff/stdscholarship",
        "source": "/stdscholarship",
        "module": "students"
      },
      {
        "label": "Fees Installment",
        "href": "/staff/fees-installment",
        "source": "/admin/fees_installment",
        "module": "fees"
      }
    ]
  },
  {
    "label": "Attendance",
    "items": [
      {
        "label": "Student Attendance",
        "href": "/staff/stuattendence",
        "source": "/admin/stuattendence",
        "module": "attendance"
      },
      {
        "label": "Approve Leave",
        "href": "/staff/approve-leave",
        "source": "/admin/approve_leave",
        "module": "hr"
      },
      {
        "label": "Attendance By Date",
        "href": "/staff/stuattendence/attendencereport",
        "source": "/admin/stuattendence/attendencereport",
        "module": "attendance"
      }
    ]
  },
  {
    "label": "Online Course",
    "items": [
      {
        "label": "Online Course",
        "href": "/staff/onlinecourse/course",
        "source": "/onlinecourse/course/index",
        "module": "lms"
      },
      {
        "label": "Offline Payment",
        "href": "/staff/onlinecourse/offlinepayment/payment",
        "source": "/onlinecourse/offlinepayment/payment",
        "module": "lms"
      },
      {
        "label": "Course Category",
        "href": "/staff/onlinecourse/coursecategory/categoryadd",
        "source": "/onlinecourse/coursecategory/categoryadd",
        "module": "lms"
      },
      {
        "label": "Question Bank",
        "href": "/staff/onlinecourse/courseexamquestion",
        "source": "/onlinecourse/courseexamquestion/index",
        "module": "lms"
      },
      {
        "label": "Online Course Report",
        "href": "/staff/onlinecourse/coursereport/report",
        "source": "/onlinecourse/coursereport/report",
        "module": "lms"
      },
      {
        "label": "Setting",
        "href": "/staff/onlinecourse/course/setting",
        "source": "/onlinecourse/course/setting",
        "module": "lms"
      }
    ]
  },
  {
    "label": "Human Resource",
    "items": [
      {
        "label": "Staff Directory",
        "href": "/staff/staff",
        "source": "/admin/staff",
        "module": "hr"
      },
      {
        "label": "Staff Attendance",
        "href": "/staff/staffattendance",
        "source": "/admin/staffattendance",
        "module": "attendance"
      },
      {
        "label": "Approve Leave Request 3",
        "href": "/staff/leaverequest",
        "source": "/admin/leaverequest/leaverequest",
        "module": "hr"
      },
      {
        "label": "Apply Leave",
        "href": "/staff/staff/leaverequest",
        "source": "/admin/staff/leaverequest",
        "module": "hr"
      },
      {
        "label": "Leave Type",
        "href": "/staff/leavetypes",
        "source": "/admin/leavetypes",
        "module": "hr"
      },
      {
        "label": "Leave Approval Setup",
        "href": "/staff/staff-leave-assign",
        "source": "/admin/staff_leave_assign",
        "module": "hr"
      },
      {
        "label": "Teachers Rating",
        "href": "/staff/staff/rating",
        "source": "/admin/staff/rating",
        "module": "hr"
      },
      {
        "label": "Department",
        "href": "/staff/department",
        "source": "/admin/department/department",
        "module": "hr"
      },
      {
        "label": "Designation",
        "href": "/staff/designation",
        "source": "/admin/designation/designation",
        "module": "hr"
      },
      {
        "label": "Disabled Staff",
        "href": "/staff/staff/disablestafflist",
        "source": "/admin/staff/disablestafflist",
        "module": "hr"
      },
      {
        "label": "Bulk Update",
        "href": "/staff/staff/staff-bulk-update",
        "source": "/admin/staff/staff_bulk_update",
        "module": "hr"
      },
      {
        "label": "Teachers Research",
        "href": "/staff/teachers-research",
        "source": "/admin/teachers_research",
        "module": "hr"
      },
      {
        "label": "Assign Mentor",
        "href": "/staff/assign-mentor",
        "source": "/admin/assign_mentor",
        "module": "mentoring"
      },
      {
        "label": "Project Approval List",
        "href": "/staff/assign-mentor/project-approval-list",
        "source": "/admin/assign_mentor/project_approval_list",
        "module": "mentoring"
      },
      {
        "label": "OJT / SIP Approval List",
        "href": "/staff/assign-mentor/ojt-approval-list",
        "source": "/admin/assign_mentor/ojt_approval_list",
        "module": "mentoring"
      },
      {
        "label": "Project Chapter List",
        "href": "/staff/assign-mentor/project-chapter-list",
        "source": "/admin/assign_mentor/project_chapter_list",
        "module": "mentoring"
      },
      {
        "label": "OJT Details",
        "href": "/staff/assign-mentor/ojt-details",
        "source": "/admin/assign_mentor/ojt_details",
        "module": "mentoring"
      },
      {
        "label": "Staff Certificate",
        "href": "/staff/staff-certificate",
        "source": "/admin/staff_certificate",
        "module": "hr"
      },
      {
        "label": "Generate Certificate",
        "href": "/staff/staff-certificate/staff-generate-certificate",
        "source": "/admin/staff_certificate/staff_generate_certificate",
        "module": "hr"
      },
      {
        "label": "Recruitment",
        "href": "/staff/hr-recruitment",
        "source": "/admin/hr_recruitment",
        "module": "hr"
      }
    ]
  },
  {
    "label": "Payroll",
    "items": [
      {
        "label": "Add Pay Element",
        "href": "/staff/staffpayroll/add-element",
        "source": "/admin/staffpayroll/add_element",
        "module": "payroll"
      },
      {
        "label": "Select Pay Element",
        "href": "/staff/staffpayroll/select-pay-element",
        "source": "/admin/staffpayroll/select_pay_element",
        "module": "payroll"
      },
      {
        "label": "Manage Staff Payroll",
        "href": "/staff/staffpayroll/manage-staff-payroll",
        "source": "/admin/staffpayroll/manage_staff_payroll",
        "module": "payroll"
      },
      {
        "label": "Generate Staff Payroll",
        "href": "/staff/staffpayroll/staff-payroll",
        "source": "/admin/staffpayroll/staff_payroll",
        "module": "payroll"
      },
      {
        "label": "Visiting Staff Payroll",
        "href": "/staff/staffpayroll/visiting-staff-payroll",
        "source": "/admin/staffpayroll/visiting_staff_payroll",
        "module": "payroll"
      },
      {
        "label": "Add Income Tax Element",
        "href": "/staff/staffpayroll/add-income-tax-element",
        "source": "/admin/staffpayroll/add_income_tax_element",
        "module": "payroll"
      },
      {
        "label": "Generate Income Tax",
        "href": "/staff/staffpayroll/generate-income-tax",
        "source": "/admin/staffpayroll/generate_income_tax",
        "module": "payroll"
      },
      {
        "label": "Setup Tax Slab",
        "href": "/staff/staffpayroll/setup-tax-slab",
        "source": "/admin/staffpayroll/setup_tax_slab",
        "module": "payroll"
      }
    ]
  },
  {
    "label": "Gmeet Live Classes",
    "items": [
      {
        "label": "Live Classes",
        "href": "/staff/gmeet/timetable",
        "source": "/admin/gmeet/timetable",
        "module": "live-classes"
      },
      {
        "label": "Live Meeting",
        "href": "/staff/gmeet/meeting",
        "source": "/admin/gmeet/meeting",
        "module": "live-classes"
      },
      {
        "label": "Live Class Report",
        "href": "/staff/gmeet/class-report",
        "source": "/admin/gmeet/class_report",
        "module": "live-classes"
      },
      {
        "label": "Live Meeting Report",
        "href": "/staff/gmeet/meeting-report",
        "source": "/admin/gmeet/meeting_report",
        "module": "live-classes"
      },
      {
        "label": "Setting",
        "href": "/staff/gmeet",
        "source": "/admin/gmeet/index",
        "module": "live-classes"
      }
    ]
  },
  {
    "label": "Zoom Live Classes",
    "items": [
      {
        "label": "Live Meeting",
        "href": "/staff/conference/meeting",
        "source": "/admin/conference/meeting",
        "module": "live-classes"
      },
      {
        "label": "Live Classes",
        "href": "/staff/conference/timetable",
        "source": "/admin/conference/timetable",
        "module": "live-classes"
      },
      {
        "label": "Live Class Report",
        "href": "/staff/conference/class-report",
        "source": "/admin/conference/class_report",
        "module": "live-classes"
      },
      {
        "label": "Live Meeting Report",
        "href": "/staff/conference/meeting-report",
        "source": "/admin/conference/meeting_report",
        "module": "live-classes"
      },
      {
        "label": "Setting",
        "href": "/staff/conference",
        "source": "/admin/conference",
        "module": "live-classes"
      }
    ]
  },
  {
    "label": "Academics",
    "items": [
      {
        "label": "Class Timetable",
        "href": "/staff/timetable/classreport",
        "source": "/admin/timetable/classreport",
        "module": "academics"
      },
      {
        "label": "Teachers Timetable",
        "href": "/staff/timetable/mytimetable",
        "source": "/admin/timetable/mytimetable",
        "module": "academics"
      },
      {
        "label": "Assign Class Teacher",
        "href": "/staff/teacher/assign-class-teacher",
        "source": "/admin/teacher/assign_class_teacher",
        "module": "academics"
      },
      {
        "label": "Assign Subject Teacher",
        "href": "/staff/teacher/assign-subject-teacher",
        "source": "/admin/teacher/assign_subject_teacher",
        "module": "academics"
      },
      {
        "label": "Promote Students",
        "href": "/staff/stdtransfer",
        "source": "/admin/stdtransfer",
        "module": "students"
      },
      {
        "label": "Semester",
        "href": "/staff/subjectgroup",
        "source": "/admin/subjectgroup",
        "module": "academics"
      },
      {
        "label": "Subjects",
        "href": "/staff/subject",
        "source": "/admin/subject",
        "module": "academics"
      },
      {
        "label": "Class",
        "href": "/staff/classes",
        "source": "/classes",
        "module": "academics"
      },
      {
        "label": "Department",
        "href": "/staff/department",
        "source": "/department",
        "module": "system"
      },
      {
        "label": "Sections",
        "href": "/staff/sections",
        "source": "/sections",
        "module": "academics"
      },
      {
        "label": "Assign Major/Minor",
        "href": "/staff/sectionwise-specialization/assign-program",
        "source": "/sectionwise_specialization/assign_program",
        "module": "academics"
      },
      {
        "label": "Program",
        "href": "/staff/course-master",
        "source": "/course_master",
        "module": "academics"
      },
      {
        "label": "Specialization",
        "href": "/staff/sectionwise-specialization",
        "source": "/sectionwise_specialization",
        "module": "academics"
      },
      {
        "label": "Program Intake",
        "href": "/staff/programintake",
        "source": "/Programintake",
        "module": "academics"
      }
    ]
  },
  {
    "label": "Assignment",
    "items": [
      {
        "label": "Add Assignment",
        "href": "/staff/homework",
        "source": "/homework",
        "module": "assignments"
      }
    ]
  },
  {
    "label": "Examinations",
    "items": [
      {
        "label": "Mark Entry Single Subject",
        "href": "/staff/examgroup/mark-entry-single-subject",
        "source": "/admin/examgroup/markEntrySingleSubject",
        "module": "examinations"
      },
      {
        "label": "Mark Entry Subjectwise",
        "href": "/staff/examgroup/mark-entry-subjectwise",
        "source": "/admin/examgroup/markEntrySubjectwise",
        "module": "examinations"
      },
      {
        "label": "Mark Entry Multi Subjectwise",
        "href": "/staff/examgroup/displaymarksexamsubjwise",
        "source": "/admin/examgroup/displaymarksexamsubjwise",
        "module": "examinations"
      },
      {
        "label": "Exam Group",
        "href": "/staff/examgroup",
        "source": "/admin/examgroup",
        "module": "examinations"
      },
      {
        "label": "Exam Schedule",
        "href": "/staff/exam-schedule",
        "source": "/admin/exam_schedule",
        "module": "examinations"
      },
      {
        "label": "ATKT Form",
        "href": "/staff/atkt-form/atkt-form-student",
        "source": "/admin/atkt_form/atkt_form_student",
        "module": "examinations"
      },
      {
        "label": "Edit ATKT Form",
        "href": "/staff/atkt-form/edit-atkt-form-student",
        "source": "/admin/atkt_form/edit_atkt_form_student",
        "module": "examinations"
      },
      {
        "label": "Exam Result",
        "href": "/staff/examresult",
        "source": "/admin/examresult",
        "module": "examinations"
      },
      {
        "label": "Backlog",
        "href": "/staff/examresult/backlog",
        "source": "/admin/examresult/backlog",
        "module": "examinations"
      },
      {
        "label": "Result Block/Unblock",
        "href": "/staff/examresult/exam-result-block-unblock",
        "source": "/admin/examresult/exam_result_block_unblock",
        "module": "examinations"
      },
      {
        "label": "Design Admit Card",
        "href": "/staff/admitcard",
        "source": "/admin/admitcard",
        "module": "examinations"
      },
      {
        "label": "Print Admit Card",
        "href": "/staff/examresult/admitcard",
        "source": "/admin/examresult/admitcard",
        "module": "examinations"
      },
      {
        "label": "Exam Type",
        "href": "/staff/examgroup/exam-type",
        "source": "/admin/examgroup/exam_type",
        "module": "examinations"
      },
      {
        "label": "Exam Form",
        "href": "/staff/examgroup/exam-form",
        "source": "/admin/examgroup/exam_form",
        "module": "examinations"
      },
      {
        "label": "Print Marksheet Format",
        "href": "/staff/exammarksheet/marksheet",
        "source": "/admin/exammarksheet/marksheet",
        "module": "examinations"
      },
      {
        "label": "Design Marksheet Format",
        "href": "/staff/exammarksheet",
        "source": "/admin/exammarksheet",
        "module": "examinations"
      },
      {
        "label": "Revaluation Form",
        "href": "/staff/examgroup/revaluation-form",
        "source": "/admin/examgroup/revaluation_form",
        "module": "examinations"
      },
      {
        "label": "Design Marksheet",
        "href": "/staff/marksheet",
        "source": "/admin/marksheet",
        "module": "examinations"
      },
      {
        "label": "Print Marksheet",
        "href": "/staff/examresult/marksheet",
        "source": "/admin/examresult/marksheet",
        "module": "examinations"
      },
      {
        "label": "Marks Grade",
        "href": "/staff/grade",
        "source": "/admin/grade",
        "module": "examinations"
      },
      {
        "label": "Relative Grade",
        "href": "/staff/grade/relative-grade",
        "source": "/admin/grade/relative_Grade",
        "module": "examinations"
      },
      {
        "label": "Result Remark",
        "href": "/staff/result-remark",
        "source": "/admin/result_remark",
        "module": "examinations"
      },
      {
        "label": "Marks Division",
        "href": "/staff/marksdivision",
        "source": "/admin/marksdivision",
        "module": "examinations"
      },
      {
        "label": "Assign Seat Number",
        "href": "/staff/student/assign-seat-number",
        "source": "/student/assign_seat_number",
        "module": "students"
      },
      {
        "label": "Paper Setting",
        "href": "/staff/papersetting",
        "source": "/admin/papersetting",
        "module": "examinations"
      },
      {
        "label": "Remuneration Setup",
        "href": "/staff/examgroup/remuneration-setup",
        "source": "/admin/examgroup/remuneration_setup",
        "module": "examinations"
      },
      {
        "label": "Exam Remuneration Bill",
        "href": "/staff/examgroup/exam-remuneration-bill",
        "source": "/admin/examgroup/exam_remuneration_bill",
        "module": "examinations"
      },
      {
        "label": "Remuneration Hour Setup",
        "href": "/staff/examgroup/remuneration-hoursetup",
        "source": "/admin/examgroup/remuneration_hoursetup",
        "module": "examinations"
      },
      {
        "label": "Remuneration Hour Setup",
        "href": "/staff/examgroup/remuneration-hoursetup",
        "source": "/admin/examgroup/remuneration_hoursetup",
        "module": "examinations"
      },
      {
        "label": "Questions Paper Creation",
        "href": "/staff/paper-creation",
        "source": "/admin/paper_creation",
        "module": "examinations"
      },
      {
        "label": "Assign Staff",
        "href": "/staff/paper-creation/assign-paper-creation",
        "source": "/admin/paper_creation/assign_paper_creation",
        "module": "examinations"
      },
      {
        "label": "Questions Paper Approve List",
        "href": "/staff/paper-creation/que-paper-approval-list",
        "source": "/admin/paper_creation/que_paper_approval_list",
        "module": "examinations"
      }
    ]
  },
  {
    "label": "Online Examinations",
    "items": [
      {
        "label": "Online Exam",
        "href": "/staff/onlineexam",
        "source": "/admin/onlineexam",
        "module": "examinations"
      },
      {
        "label": "Question Bank",
        "href": "/staff/question",
        "source": "/admin/question",
        "module": "examinations"
      }
    ]
  },
  {
    "label": "Seating Arrangement",
    "items": [
      {
        "label": "Subject Details",
        "href": "/staff/seating-arrangement",
        "source": "/seating_arrangement/index",
        "module": "examinations"
      },
      {
        "label": "Assign Block",
        "href": "/staff/seating-arrangement/assign-block",
        "source": "/seating_arrangement/assign_block",
        "module": "examinations"
      },
      {
        "label": "Report",
        "href": "/staff/seating-arrangement/report",
        "source": "/seating_arrangement/report",
        "module": "examinations"
      }
    ]
  },
  {
    "label": "Lesson Plan",
    "items": [
      {
        "label": "Copy Old Lessons",
        "href": "/staff/lessonplan/copylesson",
        "source": "/admin/lessonplan/copylesson",
        "module": "lesson-plan"
      },
      {
        "label": "Manage Lesson Plan",
        "href": "/staff/syllabus",
        "source": "/admin/syllabus",
        "module": "lesson-plan"
      },
      {
        "label": "Manage Syllabus Status",
        "href": "/staff/syllabus/status",
        "source": "/admin/syllabus/status",
        "module": "lesson-plan"
      },
      {
        "label": "Create Lesson",
        "href": "/staff/lessonplan/lesson",
        "source": "/admin/lessonplan/lesson",
        "module": "lesson-plan"
      },
      {
        "label": "Topic",
        "href": "/staff/lessonplan/topic",
        "source": "/admin/lessonplan/topic",
        "module": "lesson-plan"
      },
      {
        "label": "Instruction Plan",
        "href": "/staff/lessonplan/instruction-plan",
        "source": "/admin/lessonplan/instruction_plan",
        "module": "lesson-plan"
      }
    ]
  },
  {
    "label": "Certificate",
    "items": [
      {
        "label": "Student Certificate",
        "href": "/staff/certificate",
        "source": "/admin/certificate",
        "module": "certificates"
      },
      {
        "label": "Generate Certificate",
        "href": "/staff/generatecertificate",
        "source": "/admin/generatecertificate",
        "module": "certificates"
      },
      {
        "label": "Student ID Card",
        "href": "/staff/studentidcard",
        "source": "/admin/studentidcard",
        "module": "certificates"
      },
      {
        "label": "Generate ID Card",
        "href": "/staff/generateidcard/search",
        "source": "/admin/generateidcard/search",
        "module": "certificates"
      },
      {
        "label": "Staff ID Card",
        "href": "/staff/staffidcard",
        "source": "/admin/staffidcard",
        "module": "hr"
      },
      {
        "label": "Generate Staff ID Card",
        "href": "/staff/generatestaffidcard",
        "source": "/admin/generatestaffidcard",
        "module": "hr"
      },
      {
        "label": "Certificate Report",
        "href": "/staff/certificate-report",
        "source": "/admin/certificate_report",
        "module": "certificates"
      }
    ]
  },
  {
    "label": "Feedback Management",
    "items": [
      {
        "label": "Add Form",
        "href": "/staff/feedback/feedback-formname-master",
        "source": "/feedback/feedback_formname_master",
        "module": "feedback"
      },
      {
        "label": "Field Master",
        "href": "/staff/feedback",
        "source": "/feedback/index",
        "module": "feedback"
      },
      {
        "label": "Assign Form",
        "href": "/staff/feedback/assign-feedback-form",
        "source": "/feedback/assign_feedback_form",
        "module": "feedback"
      },
      {
        "label": "Feedback Form",
        "href": "/staff/feedback/showview-feedback-form",
        "source": "/feedback/showview_feedback_form",
        "module": "feedback"
      },
      {
        "label": "Submitted Form",
        "href": "/staff/feedback/submitted-forms",
        "source": "/feedback/submitted_forms",
        "module": "feedback"
      },
      {
        "label": "Fill Feedback Form",
        "href": "/staff/feedback/fill-feedback-form",
        "source": "/feedback/fill_feedback_form",
        "module": "feedback"
      }
    ]
  },
  {
    "label": "CO-PO",
    "items": [
      {
        "label": "Course Outcomes",
        "href": "/staff/copo/course-outcomes",
        "source": "/admin/copo/course_outcomes",
        "module": "outcomes"
      },
      {
        "label": "Program Outcomes",
        "href": "/staff/copo/program-outcomes",
        "source": "/admin/copo/program_outcomes",
        "module": "outcomes"
      },
      {
        "label": "Create Lesson",
        "href": "/staff/copo/lesson",
        "source": "/admin/copo/lesson",
        "module": "outcomes"
      },
      {
        "label": "Plan",
        "href": "/staff/copo/plan",
        "source": "/admin/copo/plan",
        "module": "outcomes"
      },
      {
        "label": "CO-PO Mapping",
        "href": "/staff/copo/co-po-mapping",
        "source": "/admin/copo/co_po_mapping",
        "module": "outcomes"
      },
      {
        "label": "TLP Approve List",
        "href": "/staff/copo/tlp-approve-list",
        "source": "/admin/copo/tlp_approve_list",
        "module": "outcomes"
      },
      {
        "label": "Indirect PO Mapping",
        "href": "/staff/copo/indirect-po-mapping",
        "source": "/admin/copo/indirect_po_mapping",
        "module": "outcomes"
      }
    ]
  },
  {
    "label": "Training & Placements",
    "items": [
      {
        "label": "Training & Placements List",
        "href": "/staff/tnp",
        "source": "/admin/tnp",
        "module": "placements"
      },
      {
        "label": "Placements Company List",
        "href": "/staff/tnp/tnp-company-list",
        "source": "/admin/tnp/tnp_company_list",
        "module": "placements"
      }
    ]
  },
  {
    "label": "Task Management",
    "items": [
      {
        "label": "Task Management",
        "href": "/staff/teacherlog",
        "source": "/teacherlog",
        "module": "hr"
      }
    ]
  },
  {
    "label": "Canteen",
    "items": [
      {
        "label": "Create Coupon",
        "href": "/staff/canteen/create-coupon",
        "source": "/admin/canteen/create_coupon",
        "module": "canteen"
      },
      {
        "label": "Canteen Auditor",
        "href": "/staff/canteen/canteen-auditor",
        "source": "/admin/canteen/canteen_auditor",
        "module": "canteen"
      },
      {
        "label": "Menu List",
        "href": "/staff/canteen/menu-list",
        "source": "/admin/canteen/menu_list",
        "module": "canteen"
      },
      {
        "label": "Assign Menu",
        "href": "/staff/canteen/assign-menu",
        "source": "/admin/canteen/assign_menu",
        "module": "canteen"
      },
      {
        "label": "Food Item Master",
        "href": "/staff/canteen/getall-food-item",
        "source": "/admin/canteen/getall_foodItem",
        "module": "canteen"
      },
      {
        "label": "Menu Type Master",
        "href": "/staff/canteen/getall-breaktype",
        "source": "/admin/canteen/getall_breaktype",
        "module": "canteen"
      },
      {
        "label": "Canteen Master",
        "href": "/staff/canteen/getall-canteen",
        "source": "/admin/canteen/getall_canteen",
        "module": "canteen"
      }
    ]
  },
  {
    "label": "Download Center",
    "items": [
      {
        "label": "Content Type",
        "href": "/staff/contenttype",
        "source": "/admin/contenttype",
        "module": "downloads"
      },
      {
        "label": "Content Share List",
        "href": "/staff/content/list",
        "source": "/admin/content/list",
        "module": "downloads"
      },
      {
        "label": "Upload /Share Content",
        "href": "/staff/content/upload",
        "source": "/admin/content/upload",
        "module": "downloads"
      },
      {
        "label": "Video Tutorial",
        "href": "/staff/video-tutorial",
        "source": "/admin/video_tutorial",
        "module": "downloads"
      }
    ]
  },
  {
    "label": "Communicate",
    "items": [
      {
        "label": "Notice Board 6",
        "href": "/staff/notification",
        "source": "/admin/notification",
        "module": "communicate"
      },
      {
        "label": "Send Email",
        "href": "/staff/mailsms/compose",
        "source": "/admin/mailsms/compose",
        "module": "communicate"
      },
      {
        "label": "Send SMS",
        "href": "/staff/mailsms/compose-sms",
        "source": "/admin/mailsms/compose_sms",
        "module": "communicate"
      },
      {
        "label": "Email / SMS Log",
        "href": "/staff/mailsms",
        "source": "/admin/mailsms/index",
        "module": "communicate"
      },
      {
        "label": "Schedule Email SMS Log",
        "href": "/staff/mailsms/schedule",
        "source": "/admin/mailsms/schedule",
        "module": "communicate"
      },
      {
        "label": "Login Credentials Send",
        "href": "/staff/student/bulkmail",
        "source": "/student/bulkmail",
        "module": "students"
      },
      {
        "label": "Email Template",
        "href": "/staff/mailsms/email-template",
        "source": "/admin/mailsms/email_template",
        "module": "communicate"
      },
      {
        "label": "SMS Template",
        "href": "/staff/mailsms/sms-template",
        "source": "/admin/mailsms/sms_template",
        "module": "communicate"
      }
    ]
  },
  {
    "label": "Front Office",
    "items": [
      {
        "label": "Admission Enquiry",
        "href": "/staff/enquiry",
        "source": "/admin/enquiry",
        "module": "front-office"
      },
      {
        "label": "Visitor Book",
        "href": "/staff/visitors",
        "source": "/admin/visitors",
        "module": "front-office"
      },
      {
        "label": "Phone Call Log",
        "href": "/staff/generalcall",
        "source": "/admin/generalcall",
        "module": "front-office"
      },
      {
        "label": "Postal Dispatch",
        "href": "/staff/dispatch",
        "source": "/admin/dispatch",
        "module": "front-office"
      },
      {
        "label": "Postal Receive",
        "href": "/staff/receive",
        "source": "/admin/receive",
        "module": "front-office"
      },
      {
        "label": "Complaint",
        "href": "/staff/complaint",
        "source": "/admin/complaint",
        "module": "front-office"
      },
      {
        "label": "Setup Front Office",
        "href": "/staff/visitorspurpose",
        "source": "/admin/visitorspurpose",
        "module": "front-office"
      },
      {
        "label": "Inward",
        "href": "/staff/inward/inward-list",
        "source": "/admin/inward/inward_list",
        "module": "front-office"
      },
      {
        "label": "Outward",
        "href": "/staff/outward/outward-list",
        "source": "/admin/outward/outward_list",
        "module": "front-office"
      }
    ]
  },
  {
    "label": "Front CMS",
    "items": [
      {
        "label": "Event",
        "href": "/staff/front/events",
        "source": "/admin/front/events",
        "module": "cms"
      },
      {
        "label": "Gallery",
        "href": "/staff/front/gallery",
        "source": "/admin/front/gallery",
        "module": "cms"
      },
      {
        "label": "News",
        "href": "/staff/front/notice",
        "source": "/admin/front/notice",
        "module": "cms"
      },
      {
        "label": "Media Manager",
        "href": "/staff/front/media",
        "source": "/admin/front/media",
        "module": "cms"
      },
      {
        "label": "Pages",
        "href": "/staff/front/page",
        "source": "/admin/front/page",
        "module": "cms"
      },
      {
        "label": "Menus",
        "href": "/staff/front/menus",
        "source": "/admin/front/menus",
        "module": "cms"
      },
      {
        "label": "Banner Images",
        "href": "/staff/front/banner",
        "source": "/admin/front/banner",
        "module": "cms"
      }
    ]
  },
  {
    "label": "Annual Calendar",
    "items": [
      {
        "label": "Set Working Days",
        "href": "/staff/holiday/set-working-days",
        "source": "/admin/holiday/set_working_days",
        "module": "hr"
      },
      {
        "label": "Set Staff Week Off",
        "href": "/staff/holiday/staff-week-off",
        "source": "/admin/holiday/staff_week_off",
        "module": "hr"
      }
    ]
  },
  {
    "label": "Student Support",
    "items": [
      {
        "label": "Student Support Topics",
        "href": "/staff/requisitions",
        "source": "/admin/requisitions",
        "module": "inventory"
      },
      {
        "label": "Student Support List",
        "href": "/staff/requisitions/load-requisition-list",
        "source": "/admin/requisitions/load_requisition_list",
        "module": "inventory"
      }
    ]
  },
  {
    "label": "Student CV",
    "items": [
      {
        "label": "Build CV",
        "href": "/staff/resume",
        "source": "/admin/resume/index",
        "module": "placements"
      },
      {
        "label": "Download CV",
        "href": "/staff/resume/download",
        "source": "/admin/resume/download",
        "module": "placements"
      }
    ]
  },
  {
    "label": "Booking System",
    "items": [
      {
        "label": "Booking System",
        "href": "/staff/roombooking/roombook",
        "source": "/roombooking/roombook",
        "module": "room-booking"
      },
      {
        "label": "Booking System Request",
        "href": "/staff/roombooking/roombook/roombookrequest",
        "source": "/roombooking/roombook/roombookrequest",
        "module": "room-booking"
      },
      {
        "label": "Booking Request List",
        "href": "/staff/roombooking/roombook/roombookrequestlist",
        "source": "/roombooking/roombook/roombookrequestlist",
        "module": "room-booking"
      }
    ]
  },
  {
    "label": "Activity Management",
    "items": [
      {
        "label": "Add Activity",
        "href": "/staff/flowmaster/add-event",
        "source": "/admin/flowmaster/add_event",
        "module": "activities"
      },
      {
        "label": "Activity List",
        "href": "/staff/flowmaster/event-list",
        "source": "/admin/flowmaster/event_list",
        "module": "activities"
      }
    ]
  },
  {
    "label": "Income",
    "items": [
      {
        "label": "Add Income",
        "href": "/staff/income",
        "source": "/admin/income",
        "module": "finance"
      },
      {
        "label": "Search Income",
        "href": "/staff/income/incomesearch",
        "source": "/admin/income/incomesearch",
        "module": "finance"
      },
      {
        "label": "Income Head",
        "href": "/staff/incomehead",
        "source": "/admin/incomehead",
        "module": "finance"
      }
    ]
  },
  {
    "label": "Expenses",
    "items": [
      {
        "label": "Add Expense",
        "href": "/staff/expense",
        "source": "/admin/expense",
        "module": "finance"
      },
      {
        "label": "Search Expense",
        "href": "/staff/expense/expensesearch",
        "source": "/admin/expense/expensesearch",
        "module": "finance"
      },
      {
        "label": "Expense Head",
        "href": "/staff/expensehead",
        "source": "/admin/expensehead",
        "module": "finance"
      }
    ]
  },
  {
    "label": "Library",
    "items": [
      {
        "label": "Book List",
        "href": "/staff/book/getall",
        "source": "/admin/book/getall",
        "module": "library"
      },
      {
        "label": "Issue - Return",
        "href": "/staff/member",
        "source": "/admin/member",
        "module": "library"
      },
      {
        "label": "Add Student",
        "href": "/staff/member/student",
        "source": "/admin/member/student",
        "module": "library"
      },
      {
        "label": "Add Staff Member",
        "href": "/staff/member/teacher",
        "source": "/admin/member/teacher",
        "module": "library"
      }
    ]
  },
  {
    "label": "Inventory",
    "items": [
      {
        "label": "Issue Item",
        "href": "/staff/issueitem",
        "source": "/admin/issueitem",
        "module": "inventory"
      },
      {
        "label": "Add Item Stock",
        "href": "/staff/itemstock",
        "source": "/admin/itemstock",
        "module": "inventory"
      },
      {
        "label": "Add Item",
        "href": "/staff/item",
        "source": "/admin/item",
        "module": "inventory"
      },
      {
        "label": "Item Category",
        "href": "/staff/itemcategory",
        "source": "/admin/itemcategory",
        "module": "inventory"
      },
      {
        "label": "Item Store",
        "href": "/staff/itemstore",
        "source": "/admin/itemstore",
        "module": "inventory"
      },
      {
        "label": "Item Supplier",
        "href": "/staff/itemsupplier",
        "source": "/admin/itemsupplier",
        "module": "inventory"
      }
    ]
  },
  {
    "label": "Transport",
    "items": [
      {
        "label": "Transpot Fee Master",
        "href": "/staff/transport/feemaster",
        "source": "/admin/transport/feemaster",
        "module": "transport"
      },
      {
        "label": "Pickup Point",
        "href": "/staff/pickuppoint",
        "source": "/admin/pickuppoint",
        "module": "transport"
      },
      {
        "label": "Routes",
        "href": "/staff/route",
        "source": "/admin/route",
        "module": "transport"
      },
      {
        "label": "Vehicles",
        "href": "/staff/vehicle",
        "source": "/admin/vehicle",
        "module": "transport"
      },
      {
        "label": "Assign Vehicle",
        "href": "/staff/vehroute",
        "source": "/admin/vehroute",
        "module": "transport"
      },
      {
        "label": "Route Pickup Point",
        "href": "/staff/pickuppoint/assign",
        "source": "/admin/pickuppoint/assign",
        "module": "transport"
      },
      {
        "label": "Student Transport Fees",
        "href": "/staff/pickuppoint/student-fees",
        "source": "/admin/pickuppoint/student_fees",
        "module": "transport"
      }
    ]
  },
  {
    "label": "Hostel",
    "items": [
      {
        "label": "Vacancy Status",
        "href": "/staff/hostel/vacancy-status",
        "source": "/admin/hostel/vacancy_status",
        "module": "hostel"
      },
      {
        "label": "Scan qrcode",
        "href": "/staff/hostel/scan-qrcode",
        "source": "/admin/hostel/scan_qrcode",
        "module": "hostel"
      },
      {
        "label": "Gatepass List",
        "href": "/staff/hostel/gatepass-list",
        "source": "/admin/hostel/gatepass_list",
        "module": "hostel"
      },
      {
        "label": "Change Room",
        "href": "/staff/hostel/change-room",
        "source": "/admin/hostel/change_room",
        "module": "hostel"
      },
      {
        "label": "Assign Room",
        "href": "/staff/hostel/assign-room",
        "source": "/admin/hostel/assign_room",
        "module": "hostel"
      },
      {
        "label": "Hostel Rooms",
        "href": "/staff/hostelroom",
        "source": "/admin/hostelroom",
        "module": "hostel"
      },
      {
        "label": "Room Type",
        "href": "/staff/roomtype",
        "source": "/admin/roomtype",
        "module": "hostel"
      },
      {
        "label": "Add Hostel",
        "href": "/staff/hostel",
        "source": "/admin/hostel",
        "module": "hostel"
      }
    ]
  },
  {
    "label": "Alumni",
    "items": [
      {
        "label": "Manage Alumni",
        "href": "/staff/alumni/alumnilist",
        "source": "/admin/alumni/alumnilist",
        "module": "alumni"
      },
      {
        "label": "Events",
        "href": "/staff/alumni/events",
        "source": "/admin/alumni/events",
        "module": "alumni"
      }
    ]
  },
  {
    "label": "NAAC",
    "items": [
      {
        "label": "NAAC Dashborad",
        "href": "/staff/naac/dashboard",
        "source": "/admin/naac/naac_dashboard",
        "module": "naac"
      },
      {
        "label": "NAAC Report",
        "href": "/staff/naac/naac-report-master",
        "source": "/admin/naac/naac_report_master",
        "module": "naac"
      },
      {
        "label": "Task Master",
        "href": "/staff/naac",
        "source": "/admin/naac/index",
        "module": "naac"
      },
      {
        "label": "Student Feedback Form",
        "href": "/staff/naac/student-feedback-list",
        "source": "/admin/naac/student_feedback_list",
        "module": "naac"
      },
      {
        "label": "Student Rating Form",
        "href": "/staff/naac/student-rating-form",
        "source": "/admin/naac/student_rating_form",
        "module": "naac"
      },
      {
        "label": "Task Allocation",
        "href": "/staff/naac/task-allocation",
        "source": "/admin/naac/task_allocation",
        "module": "naac"
      }
    ]
  },
  {
    "label": "Multi Branch",
    "items": [
      {
        "label": "Overview",
        "href": "/staff/multibranch/branch/overview",
        "source": "/admin/multibranch/branch/overview",
        "module": "multi-campus"
      },
      {
        "label": "Report",
        "href": "/staff/multibranch/finance",
        "source": "/admin/multibranch/finance/index",
        "module": "multi-campus"
      },
      {
        "label": "Setting",
        "href": "/staff/multibranch/branch/overview",
        "source": "/admin/multibranch/branch",
        "module": "multi-campus"
      }
    ]
  },
  {
    "label": "Reports",
    "items": [
      {
        "label": "Student Information",
        "href": "/staff/report/studentinformation",
        "source": "/report/studentinformation",
        "module": "students"
      },
      {
        "label": "Front Office",
        "href": "/staff/report/set-front-office-report",
        "source": "/report/setFrontOfficeReport",
        "module": "front-office"
      },
      {
        "label": "Activity Management",
        "href": "/staff/report/flowmaster-report",
        "source": "/report/flowmaster_report",
        "module": "activities"
      },
      {
        "label": "Inward",
        "href": "/staff/report/inward-report",
        "source": "/report/inward_report",
        "module": "front-office"
      },
      {
        "label": "Outward",
        "href": "/staff/report/outward-report",
        "source": "/report/outward_report",
        "module": "front-office"
      },
      {
        "label": "Teacher Achievement",
        "href": "/staff/report/teacherachievement-report",
        "source": "/report/teacherachievement_report",
        "module": "hr"
      },
      {
        "label": "Teacher's Research Publication & Awards",
        "href": "/staff/report/teacheraward-report",
        "source": "/report/teacheraward_report",
        "module": "hr"
      },
      {
        "label": "Railway Concession Report",
        "href": "/staff/report/railway-concession-report",
        "source": "/report/railway_concession_report",
        "module": "students"
      },
      {
        "label": "Staff Payroll",
        "href": "/staff/staffpayrollreports/staff-payroll",
        "source": "/staffpayrollreports/staff_payroll",
        "module": "payroll"
      },
      {
        "label": "Outcome Basis Education",
        "href": "/staff/outcome-basis-education",
        "source": "/outcome_basis_education/index",
        "module": "outcomes"
      },
      {
        "label": "Finance",
        "href": "/staff/financereports/finance",
        "source": "/financereports/finance",
        "module": "finance"
      },
      {
        "label": "Attendance",
        "href": "/staff/attendencereports/attendance",
        "source": "/attendencereports/attendance",
        "module": "attendance"
      },
      {
        "label": "Examinations",
        "href": "/staff/examresult/examinations",
        "source": "/admin/examresult/examinations",
        "module": "examinations"
      },
      {
        "label": "Online Examinations",
        "href": "/staff/onlineexam/report",
        "source": "/admin/onlineexam/report",
        "module": "examinations"
      },
      {
        "label": "Lesson Plan",
        "href": "/staff/report/lesson-plan",
        "source": "/report/lesson_plan",
        "module": "lesson-plan"
      },
      {
        "label": "Human Resource",
        "href": "/staff/report/human-resource",
        "source": "/report/human_resource",
        "module": "hr"
      },
      {
        "label": "Library",
        "href": "/staff/report/library",
        "source": "/report/library",
        "module": "library"
      },
      {
        "label": "Inventory",
        "href": "/staff/report/inventory",
        "source": "/report/inventory",
        "module": "inventory"
      },
      {
        "label": "Other Course Form",
        "href": "/staff/liberal-art/liberal-art-report",
        "source": "/admin/liberal_art/liberal_art_report",
        "module": "academics"
      },
      {
        "label": "ATKT Form",
        "href": "/staff/atkt-form/atkt-form-report",
        "source": "/admin/atkt_form/atkt_form_report",
        "module": "examinations"
      },
      {
        "label": "Transport",
        "href": "/staff/route/studenttransportdetails",
        "source": "/admin/route/studenttransportdetails",
        "module": "transport"
      },
      {
        "label": "Hostel",
        "href": "/staff/hostelroom/studenthosteldetails",
        "source": "/admin/hostelroom/studenthosteldetails",
        "module": "hostel"
      },
      {
        "label": "Alumni",
        "href": "/staff/report/alumnireport",
        "source": "/report/alumnireport",
        "module": "alumni"
      },
      {
        "label": "Payment Log",
        "href": "/staff/userlog/payment-log",
        "source": "/admin/userlog/paymentLog",
        "module": "system"
      },
      {
        "label": "User Log",
        "href": "/staff/userlog",
        "source": "/admin/userlog",
        "module": "system"
      },
      {
        "label": "Student Log Update",
        "href": "/staff/student-log-update",
        "source": "/admin/student_log_update",
        "module": "students"
      },
      {
        "label": "Audit Trail Report",
        "href": "/staff/audit",
        "source": "/admin/audit",
        "module": "system"
      },
      {
        "label": "Feedback",
        "href": "/staff/feedbackreport",
        "source": "/feedbackreport/index",
        "module": "feedback"
      },
      {
        "label": "NAAC",
        "href": "/staff/naac/naac-report",
        "source": "/admin/naac/naac_report",
        "module": "naac"
      }
    ]
  },
  {
    "label": "System Setting",
    "items": [
      {
        "label": "General Setting",
        "href": "/staff/schsettings",
        "source": "/schsettings",
        "module": "system"
      },
      {
        "label": "Session Setting",
        "href": "/staff/sessions",
        "source": "/sessions",
        "module": "system"
      },
      {
        "label": "Manage Attributes",
        "href": "/staff/attributes",
        "source": "/admin/attributes/index",
        "module": "system"
      },
      {
        "label": "Notification Setting",
        "href": "/staff/notification/setting",
        "source": "/admin/notification/setting",
        "module": "system"
      },
      {
        "label": "SMS Setting",
        "href": "/staff/smsconfig",
        "source": "/smsconfig",
        "module": "communicate"
      },
      {
        "label": "Email Setting",
        "href": "/staff/emailconfig",
        "source": "/emailconfig",
        "module": "communicate"
      },
      {
        "label": "Payment Methods",
        "href": "/staff/paymentsettings",
        "source": "/admin/paymentsettings",
        "module": "fees"
      },
      {
        "label": "Print Header Footer",
        "href": "/staff/print-headerfooter",
        "source": "/admin/print_headerfooter",
        "module": "system"
      },
      {
        "label": "Front CMS Setting",
        "href": "/staff/frontcms",
        "source": "/admin/frontcms",
        "module": "cms"
      },
      {
        "label": "Roles Permissions",
        "href": "/staff/roles",
        "source": "/admin/roles",
        "module": "system"
      },
      {
        "label": "Backup Restore",
        "href": "/staff/admin/backup",
        "source": "/admin/admin/backup",
        "module": "system"
      },
      {
        "label": "Languages",
        "href": "/staff/language",
        "source": "/admin/language",
        "module": "system"
      },
      {
        "label": "Currency",
        "href": "/staff/currency",
        "source": "/admin/currency",
        "module": "system"
      },
      {
        "label": "Users",
        "href": "/staff/users",
        "source": "/admin/users",
        "module": "system"
      },
      {
        "label": "Modules",
        "href": "/staff/module",
        "source": "/admin/module",
        "module": "system"
      },
      {
        "label": "Custom Fields",
        "href": "/staff/customfield",
        "source": "/admin/customfield",
        "module": "system"
      },
      {
        "label": "Captcha Setting",
        "href": "/staff/captcha",
        "source": "/admin/captcha",
        "module": "system"
      },
      {
        "label": "System Fields",
        "href": "/staff/systemfield",
        "source": "/admin/systemfield",
        "module": "system"
      },
      {
        "label": "Student Profile Update",
        "href": "/staff/student/profilesetting",
        "source": "/student/profilesetting",
        "module": "students"
      },
      {
        "label": "ATKT/Regular Exam Form",
        "href": "/staff/atkt-form/admissionsetting",
        "source": "/admin/atkt_form/admissionsetting",
        "module": "examinations"
      },
      {
        "label": "Revaluation Form",
        "href": "/staff/revaluation-form/revaluationformsetting",
        "source": "/admin/revaluation_form/revaluationformsetting",
        "module": "examinations"
      },
      {
        "label": "Online Admission Setting",
        "href": "/staff/onlineadmission/admissionsetting",
        "source": "/admin/onlineadmission/admissionsetting",
        "module": "admission"
      },
      {
        "label": "Other Course Form",
        "href": "/staff/liberal-art/admissionsetting",
        "source": "/admin/liberal_art/admissionsetting",
        "module": "academics"
      },
      {
        "label": "File Types",
        "href": "/staff/admin/filetype",
        "source": "/admin/admin/filetype",
        "module": "system"
      },
      {
        "label": "Sidebar Menu",
        "href": "/staff/sidemenu",
        "source": "/admin/sidemenu",
        "module": "system"
      },
      {
        "label": "System Update",
        "href": "/staff/updater",
        "source": "/admin/updater",
        "module": "system"
      },
      {
        "label": "Multi Merchant",
        "href": "/staff/paymentcategory/multimerchant",
        "source": "/admin/paymentcategory/multimerchant",
        "module": "fees"
      },
      {
        "label": "Payment Category",
        "href": "/staff/paymentcategory",
        "source": "/admin/paymentcategory",
        "module": "fees"
      },
      {
        "label": "Assign Payment Category",
        "href": "/staff/paymentcategory/assign-payment-category",
        "source": "/admin/paymentcategory/assignPaymentCategory",
        "module": "fees"
      },
      {
        "label": "Batch Setting",
        "href": "/staff/batch-settings",
        "source": "/admin/batch_settings",
        "module": "academics"
      },
      {
        "label": "Staff Leave Batches",
        "href": "/staff/leave-batch-years",
        "source": "/admin/leave_batch_years",
        "module": "hr"
      }
    ]
  }
];
export const NAV_ITEM_COUNT = NAV.reduce((n, g) => n + g.items.length, 0);
