export const PERMISSION_CATALOG: Array<{
  module: string;
  feature: string;
  action: string;
}> = [
  { module: "dashboard", feature: "home", action: "view" },
  { module: "students", feature: "profile", action: "view" },
  { module: "students", feature: "profile", action: "create" },
  { module: "students", feature: "profile", action: "edit" },
  { module: "students", feature: "profile", action: "delete" },
  { module: "students", feature: "profile", action: "export" },
  { module: "academics", feature: "session", action: "view" },
  { module: "academics", feature: "session", action: "create" },
  { module: "academics", feature: "session", action: "edit" },
  { module: "academics", feature: "department", action: "view" },
  { module: "academics", feature: "department", action: "create" },
  { module: "academics", feature: "program", action: "view" },
  { module: "academics", feature: "program", action: "create" },
  { module: "academics", feature: "class", action: "view" },
  { module: "academics", feature: "class", action: "create" },
  { module: "academics", feature: "section", action: "view" },
  { module: "academics", feature: "section", action: "create" },
  { module: "academics", feature: "subject", action: "view" },
  { module: "academics", feature: "subject", action: "create" },
  { module: "fees", feature: "collect", action: "view" },
  { module: "fees", feature: "collect", action: "collect" },
  { module: "fees", feature: "master", action: "view" },
  { module: "fees", feature: "master", action: "create" },
  { module: "fees", feature: "master", action: "edit" },
  { module: "attendance", feature: "student", action: "view" },
  { module: "attendance", feature: "student", action: "edit" },
  { module: "attendance", feature: "leave", action: "approve" },
  { module: "exams", feature: "group", action: "view" },
  { module: "exams", feature: "group", action: "create" },
  { module: "exams", feature: "marks", action: "view" },
  { module: "exams", feature: "marks", action: "edit" },
  { module: "exams", feature: "results", action: "publish" },
  { module: "exams", feature: "results", action: "approve" },
  { module: "hr", feature: "staff", action: "view" },
  { module: "hr", feature: "staff", action: "create" },
  { module: "hr", feature: "staff", action: "edit" },
  { module: "communicate", feature: "notice", action: "view" },
  { module: "communicate", feature: "notice", action: "create" },
  { module: "settings", feature: "roles", action: "view" },
  { module: "settings", feature: "roles", action: "edit" },
  { module: "settings", feature: "backup", action: "edit" },
];

export type RoleName =
  | "SuperAdmin"
  | "Registrar"
  | "Accountant"
  | "Teacher"
  | "HOD"
  | "Principal"
  | "Student"
  | "Parent";

export const SYSTEM_ROLES: RoleName[] = [
  "SuperAdmin",
  "Registrar",
  "Accountant",
  "Teacher",
  "HOD",
  "Principal",
  "Student",
  "Parent",
];

/** Role packs from erp-spec/production/permissions.md */
export const ROLE_GRANTS: Record<Exclude<RoleName, "SuperAdmin">, string[]> = {
  Teacher: [
    "dashboard.home.view",
    "students.profile.view",
    "attendance.student.view",
    "attendance.student.edit",
    "attendance.leave.approve",
    "exams.group.view",
    "exams.marks.view",
    "exams.marks.edit",
    "academics.class.view",
    "academics.section.view",
    "academics.subject.view",
    "communicate.notice.view",
  ],
  Accountant: [
    "dashboard.home.view",
    "students.profile.view",
    "fees.collect.view",
    "fees.collect.collect",
    "fees.master.view",
    "fees.master.create",
    "fees.master.edit",
    "communicate.notice.view",
  ],
  Registrar: [
    "dashboard.home.view",
    "students.profile.view",
    "students.profile.create",
    "students.profile.edit",
    "students.profile.delete",
    "students.profile.export",
    "academics.session.view",
    "academics.session.create",
    "academics.session.edit",
    "academics.department.view",
    "academics.department.create",
    "academics.program.view",
    "academics.program.create",
    "academics.class.view",
    "academics.class.create",
    "academics.section.view",
    "academics.section.create",
    "academics.subject.view",
    "academics.subject.create",
    "attendance.student.view",
    "attendance.student.edit",
    "attendance.leave.approve",
    "hr.staff.view",
    "hr.staff.create",
    "hr.staff.edit",
    "communicate.notice.view",
    "communicate.notice.create",
  ],
  HOD: [
    "dashboard.home.view",
    "students.profile.view",
    "academics.class.view",
    "academics.subject.view",
    "attendance.student.view",
    "attendance.student.edit",
    "exams.group.view",
    "exams.marks.view",
    "exams.marks.edit",
    "hr.staff.view",
    "communicate.notice.view",
  ],
  Principal: [
    "dashboard.home.view",
    "students.profile.view",
    "students.profile.create",
    "students.profile.edit",
    "students.profile.delete",
    "fees.collect.view",
    "fees.collect.collect",
    "fees.master.view",
    "fees.master.edit",
    "attendance.student.view",
    "attendance.student.edit",
    "attendance.leave.approve",
    "exams.group.view",
    "exams.group.create",
    "exams.marks.view",
    "exams.marks.edit",
    "exams.results.publish",
    "exams.results.approve",
    "hr.staff.view",
    "communicate.notice.view",
    "communicate.notice.create",
    "academics.session.view",
    "academics.class.view",
  ],
  Student: [
    "dashboard.home.view",
    "students.profile.view",
    "communicate.notice.view",
  ],
  Parent: [
    "dashboard.home.view",
    "students.profile.view",
    "communicate.notice.view",
  ],
};
